const SEND_INFO = "SEND_INFO";
const RESET_INFO = "RESET_INFO";

const ADD_PRODUCT = "ADD_PRODUCT";
const CHANGE_PRODUCT = "CHANGE_PROCUCT";
const SUM_PRODUCTS = "SUM_PRODUCTS";

const SUM_MEALS = "SUM_MEALS";
const RESET_SUM_MEALS = "RESET_SUM_MEALS";

export default {
  SEND_INFO,
  RESET_INFO,
  ADD_PRODUCT,
  CHANGE_PRODUCT,
  SUM_PRODUCTS,
  SUM_MEALS,
  RESET_SUM_MEALS
};
